package net.kdt.pojavlaunch.ui;

import android.content.res.Resources;import android.graphics.*;import android.util.LruCache;import androidx.annotation.Nullable;
import net.kdt.pojavlaunch.R;import net.kdt.pojavlaunch.Tools;import net.kdt.pojavlaunch.value.MinecraftAccount;import java.io.File;

/** UI-only isometric head renderer. Authentication, skin storage and networking remain untouched. */
public final class SkinHead3DRenderer{
 private static final LruCache<String,Bitmap>CACHE=new LruCache<String,Bitmap>(8*1024){@Override protected int sizeOf(String k,Bitmap v){return Math.max(1,v.getByteCount()/1024);}};private static final java.util.concurrent.ConcurrentHashMap<String,Integer>GEN=new java.util.concurrent.ConcurrentHashMap<>();
 private SkinHead3DRenderer(){}
 public static void invalidate(String username){if(username!=null)GEN.merge(username.toLowerCase(java.util.Locale.ROOT),1,(a,b)->a+b);}
 public static @Nullable Bitmap resolve(Resources r,@Nullable MinecraftAccount account){if(account==null||account.username==null)return fallback(r);File full=new File(Tools.DIR_DATA+"/skins/"+account.username+"_skin.png");Bitmap out=renderFile(full,account.username);if(out!=null)return out;Bitmap flat=account.getSkinFace();if(flat==null)flat=MinecraftAccount.getSkinFace(account.username);return flat!=null?flat:fallback(r);}
 public static @Nullable Bitmap resolve(Resources r,String username){if(username==null)return fallback(r);File full=new File(Tools.DIR_DATA+"/skins/"+username+"_skin.png");Bitmap out=renderFile(full,username);if(out!=null)return out;Bitmap flat=MinecraftAccount.getSkinFace(username);return flat!=null?flat:fallback(r);}
 private static Bitmap renderFile(File f,String identity){if(!f.isFile())return null;int generation=GEN.getOrDefault(identity.toLowerCase(java.util.Locale.ROOT),0);String key=f.getAbsolutePath()+":"+f.length()+":"+f.lastModified()+":"+generation;Bitmap cached=CACHE.get(key);if(cached!=null)return cached;Bitmap skin=BitmapFactory.decodeFile(f.getAbsolutePath());if(skin==null)return null;Bitmap out=render(skin);skin.recycle();if(out!=null)CACHE.put(key,out);return out;}
 private static Bitmap fallback(Resources r){Bitmap skin=BitmapFactory.decodeResource(r,R.drawable.cs_default_skin);if(skin==null)return null;Bitmap out=render(skin);if(out==null)out=MinecraftAccount.extractSkinHead(skin);skin.recycle();return out;}
 public static Bitmap render(Bitmap skin){if(skin==null||skin.getWidth()<64||skin.getWidth()%64!=0)return null;int scale=skin.getWidth()/64;if(skin.getHeight()<32*scale)return null;Bitmap out=Bitmap.createBitmap(96,96,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(out);Paint shadow=new Paint(Paint.ANTI_ALIAS_FLAG);shadow.setColor(0x55000000);c.drawOval(new RectF(15,75,82,91),shadow);PointF[]top=q(48,5,84,23,48,41,12,23),front=q(12,23,48,41,48,84,12,66),side=q(48,41,84,23,84,66,48,84);drawFace(c,skin,8,0,top);drawFace(c,skin,8,8,front);drawFace(c,skin,16,8,side);if(hatIsReal(skin)){drawFace(c,skin,40,0,expand(top,48,27,2.5f),true);drawFace(c,skin,40,8,expand(front,30,54,2.1f),true);drawFace(c,skin,48,8,expand(side,66,54,2.1f),true);}return out;}
 /** Phase 11: an overlay box that is one flat opaque colour (old editors filled the unused hat area black) is empty, exactly as the game treats it. */
 private static boolean hatIsReal(Bitmap s){int sc=Math.max(1,s.getWidth()/64);int x0=32*sc,y0=0,w=32*sc,h=16*sc;if(x0+w>s.getWidth()||y0+h>s.getHeight())return false;int first=s.getPixel(x0,y0);if((first>>>24)!=0xFF)return true;for(int y=0;y<h;y++)for(int x=0;x<w;x++){if(s.getPixel(x0+x,y0+y)!=first)return true;}return false;}
 private static PointF[]q(float...v){return new PointF[]{new PointF(v[0],v[1]),new PointF(v[2],v[3]),new PointF(v[4],v[5]),new PointF(v[6],v[7])};}
 private static PointF[]expand(PointF[]q,float cx,float cy,float amount){PointF[]o=new PointF[4];for(int i=0;i<4;i++){float dx=q[i].x-cx,dy=q[i].y-cy,len=(float)Math.sqrt(dx*dx+dy*dy);o[i]=new PointF(q[i].x+(len==0?0:dx/len*amount),q[i].y+(len==0?0:dy/len*amount));}return o;}
 private static PointF mix(PointF a,PointF b,float t){return new PointF(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t);}private static PointF bilinear(PointF[]q,float u,float v){PointF t=mix(q[0],q[1],u),b=mix(q[3],q[2],u);return mix(t,b,v);}
 private static void drawFace(Canvas c,Bitmap s,int sx,int sy,PointF[]q){drawFace(c,s,sx,sy,q,false);}
 private static void drawFace(Canvas c,Bitmap s,int sx,int sy,PointF[]q,boolean overlay){int scale=Math.max(1,s.getWidth()/64);Paint p=new Paint();p.setAntiAlias(false);p.setStyle(Paint.Style.FILL);for(int y=0;y<8;y++)for(int x=0;x<8;x++){int color=sample(s,(sx+x)*scale,(sy+y)*scale,scale);if(Color.alpha(color)==0)continue;if(overlay){if(Color.alpha(color)<128)continue;color=color|0xFF000000;}p.setColor(color);float u0=x/8f,u1=(x+1)/8f,v0=y/8f,v1=(y+1)/8f;PointF a=bilinear(q,u0,v0),b=bilinear(q,u1,v0),d=bilinear(q,u0,v1),e=bilinear(q,u1,v1);Path path=new Path();path.moveTo(a.x,a.y);path.lineTo(b.x,b.y);path.lineTo(e.x,e.y);path.lineTo(d.x,d.y);path.close();c.drawPath(path,p);}}
 private static int sample(Bitmap b,int sx,int sy,int scale){long a=0,r=0,g=0,bl=0,n=0;for(int y=0;y<scale&&sy+y<b.getHeight();y++)for(int x=0;x<scale&&sx+x<b.getWidth();x++){int c=b.getPixel(sx+x,sy+y);int alpha=Color.alpha(c);a+=alpha;r+=Color.red(c)*alpha;g+=Color.green(c)*alpha;bl+=Color.blue(c)*alpha;n+=alpha;}if(a==0)return 0;return Color.argb((int)(a/(scale*scale)),(int)(r/n),(int)(g/n),(int)(bl/n));}
}
