package net.kdt.pojavlaunch.csclient;
import android.content.Context;import net.kdt.pojavlaunch.Tools;import net.kdt.pojavlaunch.value.launcherprofiles.MinecraftProfile;import org.json.JSONObject;import java.io.*;import java.security.MessageDigest;import java.util.*;
/** Owns only launcher-managed CS Client core files; unrelated user mods are never removed. */
public final class CsClientManagedFiles{private CsClientManagedFiles(){}
 public static void installCore(Context c,CsClientCatalog.VersionEntry v,File instance)throws Exception{File mods=new File(instance,"mods");mods.mkdirs();File metaDir=new File(instance,".csclient");metaDir.mkdirs();File meta=new File(metaDir,"managed.json");File target=new File(mods,v.fileName);if(target.isFile()&&v.sha256.equalsIgnoreCase(sha256(target))){writeMeta(meta,v);return;}File temp=new File(mods,v.fileName+".part");try(InputStream in=c.getAssets().open(v.assetPath);OutputStream out=new FileOutputStream(temp)){byte[]b=new byte[65536];int n;while((n=in.read(b))>0)out.write(b,0,n);}if(!v.sha256.equalsIgnoreCase(sha256(temp))){temp.delete();throw new IOException("Bundled CS Client verification failed");}String old=null;try{if(meta.isFile())old=new JSONObject(Tools.read(meta.getAbsolutePath())).optString("file",null);}catch(Exception ignored){}if(old!=null&&!old.equals(v.fileName))new File(mods,old).delete();File[]legacy=mods.listFiles();if(legacy!=null)for(File f:legacy){String n=f.getName().toLowerCase(Locale.ROOT);if(!f.equals(temp)&&!f.equals(target)&&(n.contains("blazeclient")||n.contains("blaze-client")))f.delete();}if(target.exists())target.delete();if(!temp.renameTo(target)){org.apache.commons.io.FileUtils.copyFile(temp,target);temp.delete();}writeMeta(meta,v);}
 public static boolean ensureForProfile(Context c,MinecraftProfile p)throws Exception{if(p==null||p.name==null||!p.name.toLowerCase(Locale.ROOT).startsWith("cs client"))return false;String text=(p.lastVersionId==null?"":p.lastVersionId)+" "+p.name;CsClientCatalog.VersionEntry selected=null;for(CsClientCatalog.VersionEntry v:CsClientCatalog.fetchLatestByMinecraft())if(text.contains(v.minecraft)){selected=v;break;}if(selected==null)return false;File dir=p.resolveGameDir();if(dir==null)return false;installCore(c,selected,dir);return true;}
 private static void writeMeta(File file,CsClientCatalog.VersionEntry v)throws Exception{JSONObject o=new JSONObject();o.put("schema",1);o.put("minecraft",v.minecraft);o.put("clientVersion",v.build);o.put("file",v.fileName);o.put("sha256",v.sha256);File tmp=new File(file.getParentFile(),"managed.tmp");Tools.write(tmp.getAbsolutePath(),o.toString(2));if(file.exists())file.delete();if(!tmp.renameTo(file)){org.apache.commons.io.FileUtils.copyFile(tmp,file);tmp.delete();}}
 private static String sha256(File f)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=new FileInputStream(f)){byte[]b=new byte[65536];int n;while((n=in.read(b))>0)d.update(b,0,n);}StringBuilder s=new StringBuilder();for(byte x:d.digest())s.append(String.format(Locale.ROOT,"%02x",x));return s.toString();}
}
